import { TutorialConfig } from '../components/CortexTutorialModal';

export const TUTORIAL_CONFIGS: Record<string, TutorialConfig> = {
  sprint: {
    gameTitle: 'Neuro Sprint',
    purpose: 'Train mental arithmetic and processing speed.',
    howItWorks: [
      'A math question appears.',
      'Choose the correct answer from 4 options.',
      'Answer quickly and accurately.',
      'The next question appears instantly.',
    ],
    example: '27 + 18 = 45',
    proTip: 'Look for shortcuts such as:\n• ×25 = ×100 ÷ 4\n• ×50 = ×100 ÷ 2',
    ctaText: 'Start Sprint',
  },
  fastFirst: {
    gameTitle: 'Fast & First Duels',
    purpose: 'Train reaction speed and accurate mental calculation.',
    howItWorks: [
      'You and your opponent see the same question.',
      'The first correct answer wins the round.',
      'Wrong answers cause a short penalty.',
    ],
    example: '9 × 8 = 72',
    proTip: 'Do not tap immediately. A correct answer is worth more than a fast mistake.',
    ctaText: 'Start Duel',
  },
  sudoku: {
    gameTitle: 'Sudoku Duels',
    purpose: 'Train logical deduction and concentration.',
    howItWorks: [
      'Fill the missing numbers.',
      'Each row must contain every number once.',
      'Each column must contain every number once.',
      'Complete the grid before your opponent.',
    ],
    example: '1 _ 3 4 → Missing number = 2',
    proTip: 'Check both the row and the column before placing a number.',
    ctaText: 'Start Sudoku',
  },
  crossMath: {
    gameTitle: 'Cross Math Duels',
    purpose: 'Train arithmetic reasoning and constraint solving.',
    howItWorks: [
      'Fill empty cells.',
      'Every row must reach its target.',
      'Every column must reach its target.',
      'Use addition, subtraction, multiplication, or division.',
    ],
    example: '4 + ? + 6 = 15 → Missing number = 5',
    proTip: 'Solve the row with the fewest empty cells first.',
    ctaText: 'Start Cross Math',
  },
  kenken: {
    gameTitle: 'KenKen Duels',
    purpose: 'Train logic and arithmetic together.',
    howItWorks: [
      'Fill the grid with unique numbers.',
      'Rows cannot repeat numbers.',
      'Columns cannot repeat numbers.',
      'Each cage must satisfy its target and operation.',
    ],
    example: '6+ means the cage numbers must add to 6.',
    proTip: 'Use the cage rule and the row rule together.',
    ctaText: 'Start KenKen',
  },
  mathMaze: {
    gameTitle: 'Math Maze Duels',
    purpose: 'Train planning and mental arithmetic.',
    howItWorks: [
      'Start with a number.',
      'Choose operations to move through the maze.',
      'Reach the target number.',
      'The shortest correct path is best.',
    ],
    example: 'Start 10 → ×2 → 20 → +5 → 25',
    proTip: 'Look for multiplication shortcuts before adding many small numbers.',
    ctaText: 'Start Maze',
  },
  mindSnap: {
    gameTitle: 'Mind Snap Duels',
    purpose: 'Train visual memory and attention.',
    howItWorks: [
      'Symbols appear briefly.',
      'Remember them.',
      'They disappear.',
      'Select the symbols you saw.',
    ],
    example: '★ ▲ ■ ●',
    proTip: 'Group symbols mentally instead of memorizing them one by one.',
    ctaText: 'Start Mind Snap',
  },
  flashAnzan: {
    gameTitle: 'Flash Anzan Duels',
    purpose: 'Train working memory and rapid mental addition.',
    howItWorks: [
      'Numbers flash quickly.',
      'Keep a running total in your mind.',
      'Enter the final sum.',
    ],
    example: '12 → 7 → 9 → Final answer = 28',
    proTip: 'Update the total immediately after each flash.',
    ctaText: 'Start Flash Anzan',
  },
  ability: {
    gameTitle: 'Ability Duels',
    purpose: 'Train overall mental agility.',
    howItWorks: [
      'Each round is different.',
      'You may get math, logic, memory, estimation, or pattern challenges.',
      'Adapt quickly.',
      'Win more rounds than your opponent.',
    ],
    example: '48 × 25 → Shortcut: ×100 ÷ 4',
    proTip: 'Think smart before thinking fast.',
    ctaText: 'Start Ability Duel',
  },
};
